export enum ScannerTicketResult {
  READY_TO_ADMIT = 'READY_TO_ADMIT',
  ENTRY_GRANTED = 'ENTRY_GRANTED',
  ALREADY_SCANNED = 'ALREADY_SCANNED',
  CANCELLED = 'CANCELLED',
  NOT_YET_VALID = 'NOT_YET_VALID',
  ENTRY_WINDOW_CLOSED = 'ENTRY_WINDOW_CLOSED',
  INVALID_FOR_EVENT = 'INVALID_FOR_EVENT',
  INVALID = 'INVALID',
}
